### ISSUE TITLE
FOUNDATIONS: Add support for CancellationToken

### ISSUE THREAD

**Issue by kenrms** [hassanhabib/RESTFulSense#24]
The `IRESTFulApiFactoryClient` currently has no overloads to support using a `CancellationToken` in API calls like the normal HttpClient, e.g. [HttpClient.GetAsync(String, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=net-5.0#System_Net_Http_HttpClient_GetAsync_System_String_System_Threading_CancellationToken_). 

I'd like to use it like such: `this.restfulApiClient.GetContentAsync<T>(relativeUrl, cancellationToken)`.

**Comment by hassanhabib** [comment]
@kenrms thanks we'll take care of it.

**Comment by hassanhabib** [comment]
@kenrms all done. give it a shot and let me know if you see any issues. thanks. great suggestions.
