### ISSUE TITLE
SERVICES: Add service method to set the HttpClient Authorization header

### ISSUE THREAD

**Issue by mabroukmahdhi** [hassanhabib/RESTFulSense#35]
Hello,

Is it possible to add (or maybe there is) a way to set the `Authorization` request header to the `httpClient` inside `RESTFulApiFactoryClient`

Mybe something like that:
```cs
public void SetAuthenticationHeaderValue(AuthenticationHeaderValue authenticationHeaderValue)
            => this.httpClient.DefaultRequestHeaders.Authorization = authenticationHeaderValue;
``` 

Thanks!

**Comment by hassanhabib** [comment]
Why not just set it in the `httpClient` you pass in during the instantiation of RESTfulSenseFactory

**Comment by mabroukmahdhi** [comment]
Thank you  @hassanhabib 

Now I have it working in my code 🌷
