### ISSUE TITLE
Error Self referencing.

### ISSUE THREAD

**Issue by nibraso** [hassanhabib/RESTFulSense#36]
I get an error `Self referencing loop detected for property 'X' with type 'XX'`.
My method in ApiBroker:

`private async ValueTask<T> PutAsync<T>(string relativeUrl, T content)`
        ` {`
               ` return await apiCient.PutContentAsync(relativeUrl, content);`
        ` }`
Before I used  `System.Text.Json` and to go around this error, I just create `JsonSerializerOptions` where `ReferenceHandler = ReferenceHandler.IgnoreCycles` and then I send this option with `PutAsJsonAsync` like this:
`JsonSerializerOptions options = new() 
            {
                ReferenceHandler = ReferenceHandler.IgnoreCycles
            };`
`await client.PutAsJsonAsync(url, obj, options);`
My question: 
How can I add this option in `PutAsync`?
Thanks.

**Comment by hassanhabib** [comment]
@nibraso this is a problem in your API models - they have self-referencing design issue. not a RESTFulSense problem.
